name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  PHP_VERSION: '8.3'

jobs:
  auto-review:
    name: Auto review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Install dependencies
        run: composer update --no-progress --optimize-autoloader

      - name: Run review
        run: composer review

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Install dependencies
        run: composer update --no-progress --optimize-autoloader

      - name: Clean up Docker
        run: docker system prune -f

      - name: Create Docker network
        run: docker network create account_default

      - name: Create Docker volume for migrations
        run: docker volume create account-adm-migrations

      - name: Run tests
        run: |
          docker run -u root --rm -it \
            --name account-test \
            --network=account_default \
            -v ${PWD}:/app \
            -v ${PWD}/config/database/mysql/migrations:/account-adm-migrations \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /app \
            gustavofreze/php:${{ env.PHP_VERSION }} bash -c "composer tests"
